### ISSUE TITLE
(Auth) Email format validation.

### ISSUE THREAD

**Issue by bmc1995** [bmc1995/vreact#17]
The Signup and Login forms should validate the email input

**Comment by DamarisTorrent** [comment]
@bmc1995 I would like to work this issue, thank you

**Comment by bmc1995** [comment]
> @bmc1995 I would like to work this issue, thank you

Hey @DamarisTorrent,  I've already developed a solution that I plan to upload shortly. However I'd really value your input and would appreciate it if you could review the code once it's up if you have the time.

**Comment by DamarisTorrent** [comment]
Sure thing, I worked up a solution too, I have it forked and branched and will submit a PR if you want to take a look, we can compare each other’s code?
